name: OpenAPI

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  openapi:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xml
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: OpenAPI checker
        run: build/openapi-checker.sh
